### ISSUE TITLE
记一次树莓派烧录 ubuntu 系统

### ISSUE THREAD

**Issue by joephon** [joephon/blog#20]
### 准备工作

- 树莓派 4B/1G/2G/4G
- TF 卡 8G 以上
- TF 读卡器
- Ubuntu for 树莓派
- Mac OS

#### 插入 TF 卡并格式化

```
diskutil list
```

找到 TF 卡挂载点

```
diskutil eraseDisk FAT32 PI_Volume  MBRFormat /dev/disk3
```

#### 卸载 TF 卡

```
diskutil unmountDisk /dev/disk3
```

#### 烧录系统

```
dd if=/path/to/your/img of=/path/to/your/tfcard bs=32m
```

如果mac上烧录缓慢，试下 把/dev/disk{n} 换成 /dev/rdisk{n}

弹出 TF 卡 插入树莓派 

树莓派插入网线、键盘、显示器然后开机

#### Bingo～ Done！

默认账号和密码都是ubuntu 初次登录系统会要求初始化

设置时区

```
sudo cp /usr/share/zoneinfo/Asia/Shanghai  /etc/localtime
```

更换阿里云源

```
sudo sed -i 's/ports.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list
```

更新系统 & 安装net-tools

```
sudo apt update
sudo apt install net-tools -y
sudo apt install bluetooth -y
```

启动蓝牙

```
sudo hciattach /dev/ttyAMA0 any
sudo bluetoothctl
power on
discoverable on
scan on
```

 搜索蓝牙&配对

```
show
devices
connect {id}
```

配置wifi

```
sudo apt install wireless-tools -y
sudo apt install iw -y
sudo ip link set wlan0 up
```
上面只是工具 可选

```
sudo vim /etc/netplan/50-cloud-init.yaml


network:
    ethernets:
        eth0:
            dhcp4: false
            addresses: [10.200.12.222/24]
            gateway4: 10.200.12.254
            nameservers:
                    addresses: [10.200.10.1,10.200.10.2]
           # option:true
    wifis:
            wlan0:
                    dhcp4: true
                    access-points:
                            "ssid":
                                    password: "password"
    version: 2
```

测试

```
sudo netplan --debug apply
```

done!
